//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.16 at 05:35:03 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "uri:oozie:hive-action:0.5", elementFormDefault = XmlNsForm.QUALIFIED,
        xmlns = {
                @XmlNs(prefix = "hive", namespaceURI = "uri:oozie:hive-action:0.5")
        }
)
package ru.sberbank.bigdata.cloud.rb.internal.sources.generator.api.oozie.entities.source.hive_action;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlNsForm;