//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.16 at 05:35:03 PM MSK 
//


package ru.sberbank.bigdata.cloud.rb.internal.sources.generator.api.oozie.entities.source.spark_action;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.sberbank.bigdata.cloud.rb.internal.sources.common.oozie.entities.spark_action package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Spark_QNAME = new QName("uri:oozie:spark-action:0.1", "spark");

    /**
     * Create an instance of {@link CONFIGURATION }
     * 
     */
    public CONFIGURATION createCONFIGURATION() {
        return new CONFIGURATION();
    }

    /**
     * Create an instance of {@link ACTION }
     * 
     */
    public ACTION createACTION() {
        return new ACTION();
    }

    /**
     * Create an instance of {@link DELETE }
     * 
     */
    public DELETE createDELETE() {
        return new DELETE();
    }

    /**
     * Create an instance of {@link PREPARE }
     * 
     */
    public PREPARE createPREPARE() {
        return new PREPARE();
    }

    /**
     * Create an instance of {@link MKDIR }
     * 
     */
    public MKDIR createMKDIR() {
        return new MKDIR();
    }

    /**
     * Create an instance of {@link CONFIGURATION.Property }
     * 
     */
    public CONFIGURATION.Property createCONFIGURATIONProperty() {
        return new CONFIGURATION.Property();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ACTION }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:oozie:spark-action:0.1", name = "spark")
    public JAXBElement<ACTION> createSpark(ACTION value) {
        return new JAXBElement<ACTION>(_Spark_QNAME, ACTION.class, null, value);
    }

}
