log4j.rootLogger=INFO,console,httpAppender

log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.target=System.out
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d{yy/MM/dd HH:mm:ss} %p %c{10}: %m%n

#log4j.appender.flumeAppender=ru.sberbank.cm.httpappender.HttpAppender
#log4j.appender.flumeAppender.appId=masspers-b0d5-414b-b597-f3cc984fa0f8
#log4j.appender.flumeAppender.typeIds==AUDIT:Audit,Audit:Audit,[AUDIT]:Audit
#log4j.appender.flumeAppender.url=http://localhost:44441
#log4j.appender.flumeAppender.dynamicTypeId=true
#log4j.appender.flumeAppender.layout=org.apache.log4j.PatternLayout
#log4j.appender.flumeAppender.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
#log4j.appender.flumeAppender.connectionTimeout=100
#log4j.appender.flumeAppender.keepAliveTimeout=10000
#log4j.appender.flumeAppender.numRetries=2
#log4j.appender.flumeAppender.batchSize=50
#log4j.appender.flumeAppender.messageQueueCapacity=10000
#log4j.appender.flumeAppender.ignoreExceptions=true
#log4j.appender.flumeAppender.defaultTypeId=masspers_default_type_id
#log4j.appender.flumeAppender.queueType=memory
#log4j.appender.flumeAppender.printToStdOut=false

log4j.appender.httpAppender=ru.sberbank.cm.httpappender.HttpAppender
log4j.appender.httpAppender.appId=masspers-b0d5-414b-b597-f3cc984fa0f8
#log4j.appender.httpAppender.typeIds=AUDIT:Audit,Audit:Audit,[AUDIT]:Audit
log4j.appender.httpAppender.url=http://localhost:44441
log4j.appender.httpAppender.layout=org.apache.log4j.PatternLayout
log4j.appender.httpAppender.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
#log4j.appender.httpAppender.dynamicTypeId=true
log4j.appender.httpAppender.defaultTypeId=masspers_default_type_id
log4j.appender.httpAppender.queueType=memory
log4j.appender.httpAppender.printToStdOut=false
log4j.appender.httpAppender.connectionTimeout=1000
log4j.appender.httpAppender.keepAliveTimeout=10000
log4j.appender.httpAppender.numRetries=5
log4j.appender.httpAppender.batchSize=50
log4j.appender.httpAppender.messageQueueCapacity=10000

#?????????????? ?????????
#log4j.appender.httpAppender.typeId=Audit
#log4j.appender.httpAppender.subTypeId=A0

external.log.level=WARN
graphite.log.level=ERROR

log4j.logger.HQLRHSemantic=${external.log.level}
log4j.logger.org.apache.spark.SparkEnv=${external.log.level}
log4j.logger.org.apache.spark.ContextCleaner=${external.log.level}
log4j.logger.org.apache.spark.util.ShutdownHookManager=${external.log.level}
log4j.logger.org.apache.spark.MapOutputTrackerMasterEndpoint=${external.log.level}
log4j.logger.org.apache.spark.spark.MapOutputTrackerMaster=${external.log.level}

log4j.logger.org.apache.spark.scheduler.TaskSetManager=${external.log.level}
log4j.logger.org.apache.spark.scheduler.DAGScheduler=${external.log.level}
log4j.logger.org.apache.spark.scheduler.cluster.YarnClusterScheduler=${external.log.level}
log4j.logger.org.apache.spark.scheduler.cluster.YarnClusterSchedulerBackend=${external.log.level}
log4j.logger.org.apache.spark.scheduler.EventLoggingListener=${external.log.level}

log4j.logger.org.apache.spark.storage.BlockManager=${external.log.level}
log4j.logger.org.apache.spark.storage.BlockManagerMaster=${external.log.level}
log4j.logger.org.apache.spark.storage.DiskBlockManager=${external.log.level}
log4j.logger.org.apache.spark.storage.BlockManagerMasterEndpoint=${external.log.level}
log4j.logger.org.apache.spark.storage.BlockManagerInfo=${external.log.level}
log4j.logger.org.apache.spark.storage.MemoryStore=${external.log.level}

log4j.logger.org.apache.spark.deploy.yarn.ExecutorRunnable=${external.log.level}
log4j.logger.org.apache.spark.deploy.yarn.YarnAllocator=${external.log.level}

log4j.logger.org.apache.spark.sql.catalyst.expressions.codegen.GenerateUnsafeProjection=${external.log.level}
log4j.logger.org.apache.spark.sql.catalyst.parser.CatalystSqlParser=${external.log.level}
log4j.logger.org.apache.spark.sql.hive.client.ClientWrapper=${external.log.level}
log4j.logger.org.apache.spark.sql.hive.SparkSession=${external.log.level}
log4j.logger.org.apache.spark.sql.execution.datasources.parquet.ParquetRelation=${external.log.level}
log4j.logger.org.apache.spark.sql.execution.datasources.DefaultWriterContainer=${external.log.level}

log4j.logger.org.apache.spark.util.Utils=${external.log.level}
log4j.logger.org.apache.spark.ui.JettyUtils=${external.log.level}
log4j.logger.org.apache.spark.network.netty.NettyBlockTransferService=${external.log.level}

log4j.logger.org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy=${external.log.level}
log4j.logger.org.apache.hadoop.yarn.client.api.impl.AMRMClientImpl=${external.log.level}

log4j.logger.org.apache.hadoop.hive.ql.Driver=${external.log.level}
log4j.logger.org.apache.hadoop.hive.ql.session.SessionState=${external.log.level}
log4j.logger.org.apache.hadoop.hive.ql.log.PerfLogger=${external.log.level}

log4j.logger.org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter=${external.log.level}

log4j.logger.org.spark-project.jetty.util.component.AbstractLifeCycle=${external.log.level}
log4j.logger.org.spark-project.jetty.server.handler.ContextHandler=${external.log.level}

log4j.logger.hive.ql.metadata.Hive=${external.log.level}
log4j.logger.hive.metastore=${external.log.level}
log4j.logger.Remoting=${external.log.level}
log4j.logger.com.codahale.metrics.graphite.GraphiteReporter=${graphite.log.level}