include "application"

b2c {
  sql {
    function {
      path = ["${b2c.sql.external.function.path}"]
      definition = {
        spark = {
        }
      }
    }
    udf {
      path = ["${b2c.sql.external.udf.path}"]
    }
  }
}