### Настройки DevSecOps ###
domain: "DELTA"
### Общая информация о командах ###
team:
  # код команды в МУСе
  - {
    mus_code: "00O70027",
      # название команды в МУСе
    mus_name: "DataBatch",
    # почтовый адрес Product Owner в МУСе для уведомлений с результатами сканирования. Возможно указание нескольких email через ;
    mus_po_mail: "SAShustova@sberbank.ru",
  }

### Общая информация о приложении ###
app:
  # Конфигурационный элемент (КЭ) приложения / модуля ПО в Service Manager, под которым проходят релизы (не указывать КЭ ИТ-услуги).
  # !!! КЭ должен быть строкой, состоящей исключительно из цифр без лидирующих нулей !!!
  sm_id: "2364774"
  # название КЭ приложения / модуля ПО в Service Manager
  sm_name: "CВД РБ Витрина на данных Greenplum ЕВК"

### Настройки SAST Checkmarx ###
sast_cx:
  # проектная область в JIRA для заведения и синхронизации дефектов
  jira_area: "DATABATCH"
  # маски файлов и директорий для включения (**/*) в скан и исключения (!**/*) из скана. Пример: "!**/utils/**/*.xml" - исключение всех xml файлов в папке utils
  # В данном пункте требуется исключить все, что не поддерживает инструмент, либо не идет в релиз (тесты, файлы окружения и др). Актуальный список поддерживаемых языков можно найти в FAQ QG по SAST
  # Внимание! Если вы используете SQL диалект не PL/SQL (Oracle), то требуется также исключить файлы SQL
  # Пример 1: "!**/*.sql, !**/*.spec" - исключение всех файлов SQL, а также .spec
  # Пример 2: "!**/utils/**/*.xml" - исключение всех xml файлов в папке utils
  # Внимание! Есть кейсы, когда в при сборке приложения в рабочую область Jenkins помимо кода репозитория подтягиваются внешние сущности (библиотеки python, директории venv и др)
  # В таком случае нужно выполнять проверку SAST до сборки, очищать рабочую область, либо добавить сюда в маски необходимые папки, чтобы SAST не проводил их сканирование
  masks: "!**/*.sql"
  # id профиля сканирования, по умолчанию 100012. 14 - для мобильного приложения, 100003 - Smoke
  # Внимание! Если вы используете мобильный пресет, то необходимо сканировать AndroidManifest.xml
  preset_id: "100012"
  # макс время ожидания статуса QG в минутах
  wait_qg: "0"
  # Вывод отладочных логов плагина Checkmarx
  # Опциональный параметр. Возможные значения: true или false. По умолчанию - false
  debug: false

### Настройки OSS
oss:
  # Маски файлов и директорий для исключения из сканирования
  # Пример: "**/utils/**/*.xml" - исключение всех xml файлов во всех папках utils
  # !!! Перечисление нескольких масок возможно через знаки "," или ";" внутри одной строки, например, "**/*test*/**; **/*.txt, .git/**" !!!
  # !!! Пропуски в каждой маске справа и слева автоматически удалятся (trim) !!!
  excludes: ""