com.sun.security.jgss.krb5.initiate {
   com.sun.security.auth.module.Krb5LoginModule required
   useKeyTab=true
   useTicketCache=true
   doNotPrompt=true
   refreshKrb5Config=true
   keyTab="./u_utsklsdprozn2_s_custom_rb_kurscur.keytab"
   principal="u_utsklsdprozn2_s_custom_rb_kurscur@DF.SBRF.RU";
};
