com.sun.security.jgss.krb5.initiate {
   com.sun.security.auth.module.Krb5LoginModule required
   useKeyTab=true
   useTicketCache=true
   doNotPrompt=true
   refreshKrb5Config=true
   keyTab="./u_sklsdprozn_s_custom_rb_sbol.keytab"
   principal="u_sklsdprozn_s_custom_rb_sbol@DEV.DF.SBRF.RU";
};
