com.sun.security.jgss.krb5.initiate {
   com.sun.security.auth.module.Krb5LoginModule required
   useKeyTab=true
   useTicketCache=true
   doNotPrompt=true
   refreshKrb5Config=true
   keyTab="./u_arnsdprozn_s_custom_rb_bo.keytab"
   principal="u_arnsdprozn_s_custom_rb_bo@DF.SBRF.RU";
};
