com.sun.security.jgss.krb5.initiate {
   com.sun.security.auth.module.Krb5LoginModule required
   useKeyTab=true
   useTicketCache=true
   doNotPrompt=true
   refreshKrb5Config=true
   keyTab="./u_utarnsdprozn_s_custom_rb_card.keytab"
   principal="u_utarnsdprozn_s_custom_rb_card@DF.SBRF.RU";
};
