com.sun.security.jgss.krb5.initiate {
   com.sun.security.auth.module.Krb5LoginModule required
   useKeyTab=true
   useTicketCache=true
   doNotPrompt=true
   refreshKrb5Config=true
   keyTab="./u_itsklsdprozn_s_custom_rozn_evo.keytab"
   principal="u_itsklsdprozn_s_custom_rozn_evo@DEV.DF.SBRF.RU";
};
