package ru.sberbank.bigdata.cloud.rb.internal.sources.common.constants;

import org.apache.spark.sql.types.DecimalType;

import static org.apache.spark.sql.types.DataTypes.createDecimalType;

public class DecimalTypes {
    public static final DecimalType DECIMAL_1_0 = createDecimalType(1, 0);
    public static final DecimalType DECIMAL_2_0 = createDecimalType(2, 0);
    public static final DecimalType DECIMAL_3_0 = createDecimalType(3, 0);
    public static final DecimalType DECIMAL_4_0 = createDecimalType(4, 0);
    public static final DecimalType DECIMAL_5_0 = createDecimalType(5, 0);
    public static final DecimalType DECIMAL_5_2 = createDecimalType(5, 2);
    public static final DecimalType DECIMAL_5_4 = createDecimalType(5, 4);
    public static final DecimalType DECIMAL_6_0 = createDecimalType(6, 0);
    public static final DecimalType DECIMAL_6_2 = createDecimalType(6, 2);
    public static final DecimalType DECIMAL_7_2 = createDecimalType(7, 2);
    public static final DecimalType DECIMAL_8_0 = createDecimalType(8, 0);
    public static final DecimalType DECIMAL_9_0 = createDecimalType(9, 0);
    public static final DecimalType DECIMAL_10_0 = createDecimalType(10, 0);
    public static final DecimalType DECIMAL_11_0 = createDecimalType(11, 0);
    public static final DecimalType DECIMAL_11_8 = createDecimalType(11, 8);
    public static final DecimalType DECIMAL_12_0 = createDecimalType(12, 0);
    public static final DecimalType DECIMAL_12_2 = createDecimalType(12, 2);
    public static final DecimalType DECIMAL_12_6 = createDecimalType(12, 6);
    public static final DecimalType DECIMAL_15_0 = createDecimalType(15, 0);
    public static final DecimalType DECIMAL_15_2 = createDecimalType(15, 2);
    public static final DecimalType DECIMAL_15_4 = createDecimalType(15, 4);
    public static final DecimalType DECIMAL_15_5 = createDecimalType(15, 5);
    public static final DecimalType DECIMAL_15_6 = createDecimalType(15, 6);
    public static final DecimalType DECIMAL_15_8 = createDecimalType(15, 8);
    public static final DecimalType DECIMAL_16_8 = createDecimalType(16, 8);
    public static final DecimalType DECIMAL_17_2 = createDecimalType(17, 2);
    public static final DecimalType DECIMAL_18_0 = createDecimalType(18, 0);
    public static final DecimalType DECIMAL_18_2 = createDecimalType(18, 2);
    public static final DecimalType DECIMAL_18_4 = createDecimalType(18, 4);
    public static final DecimalType DECIMAL_18_6 = createDecimalType(18, 6);
    public static final DecimalType DECIMAL_18_8 = createDecimalType(18, 8);
    public static final DecimalType DECIMAL_19_0 = createDecimalType(19, 0);
    public static final DecimalType DECIMAL_19_2 = createDecimalType(19, 2);
    public static final DecimalType DECIMAL_19_4 = createDecimalType(19, 4);
    public static final DecimalType DECIMAL_20_0 = createDecimalType(20, 0);
    public static final DecimalType DECIMAL_20_4 = createDecimalType(20, 4);
    public static final DecimalType DECIMAL_20_6 = createDecimalType(20, 6);
    public static final DecimalType DECIMAL_20_10 = createDecimalType(20, 10);
    public static final DecimalType DECIMAL_22_2 = createDecimalType(22, 2);
    public static final DecimalType DECIMAL_22_12 = createDecimalType(22, 12);
    public static final DecimalType DECIMAL_23_0 = createDecimalType(23, 0);
    public static final DecimalType DECIMAL_23_5 = createDecimalType(23, 5);
    public static final DecimalType DECIMAL_24_5 = createDecimalType(24, 5);
    public static final DecimalType DECIMAL_25_0 = createDecimalType(25, 0);
    public static final DecimalType DECIMAL_25_4 = createDecimalType(25, 4);
    public static final DecimalType DECIMAL_26_0 = createDecimalType(26, 0);
    public static final DecimalType DECIMAL_26_2 = createDecimalType(26, 2);
    public static final DecimalType DECIMAL_27_2 = createDecimalType(27, 2);
    public static final DecimalType DECIMAL_28_0 = createDecimalType(28, 0);
    public static final DecimalType DECIMAL_28_2 = createDecimalType(28, 2);
    public static final DecimalType DECIMAL_28_8 = createDecimalType(28, 8);
    public static final DecimalType DECIMAL_28_10 = createDecimalType(28, 10);
    public static final DecimalType DECIMAL_28_14 = createDecimalType(28, 14);
    public static final DecimalType DECIMAL_29_4 = createDecimalType(29, 4);
    public static final DecimalType DECIMAL_29_10 = createDecimalType(29, 10);
    public static final DecimalType DECIMAL_30_10 = createDecimalType(30, 10);
    public static final DecimalType DECIMAL_31_10 = createDecimalType(31, 10);
    public static final DecimalType DECIMAL_33_5 = createDecimalType(33, 5);
    public static final DecimalType DECIMAL_34_5 = createDecimalType(34, 5);
    public static final DecimalType DECIMAL_35_5 = createDecimalType(35, 5);
    public static final DecimalType DECIMAL_35_8 = createDecimalType(35, 8);
    public static final DecimalType DECIMAL_36_4 = createDecimalType(36, 4);
    public static final DecimalType DECIMAL_38_0 = createDecimalType(38, 0);
    public static final DecimalType DECIMAL_38_2 = createDecimalType(38, 2);
    public static final DecimalType DECIMAL_38_4 = createDecimalType(38, 4);
    public static final DecimalType DECIMAL_38_5 = createDecimalType(38, 5);
    public static final DecimalType DECIMAL_38_6 = createDecimalType(38, 6);
    public static final DecimalType DECIMAL_38_8 = createDecimalType(38, 8);
    public static final DecimalType DECIMAL_38_12 = createDecimalType(38, 12);
    public static final DecimalType DECIMAL_38_10 = createDecimalType(38, 10);
    public static final DecimalType DECIMAL_38_15 = createDecimalType(38, 15);
    public static final DecimalType DECIMAL_38_16 = createDecimalType(38, 16);
    public static final DecimalType DECIMAL_38_18 = createDecimalType(38, 18);
    public static final DecimalType DECIMAL_38_21 = createDecimalType(38, 21);
    public static final DecimalType DECIMAL_38_22 = createDecimalType(38, 22);
    public static final DecimalType DECIMAL_38_26 = createDecimalType(38, 26);
}
