GpClient {
   com.sun.security.auth.module.Krb5LoginModule required
   useKeyTab=true
   keyTab="./u_utsklgrnplm_s_vd_rozn_mpp_daas_tech.keytab"
   storeKey=true
   useTicketCache=false
   principal="u_utsklgrnplm_s_vd_rozn_mpp_daas_tech@DF.SBRF.RU";
};