b2c {
  sql {
    secman {
      auth.path = "/v1/auth/approle/login"
      ctl {
        passphrase: "{{ secman_passphrase }}"
        email: "{{ secman_email }}"
        common-name: "{{ secman_common_name }}"
        path: "{{ secman_path }}"
      }
      appender {
        passphrase: "{{ secman_passphrase }}"
        email: "{{ secman_email }}"
        common-name: "{{ secman_common_name }}"
        path: "{{ secman_path }}"
      }
    }
    appender.url = "{{ appender_url }}"
    appender.passphrase = "{{ appender_passphrase }}"
  }
}