WITH monthly AS (
    SELECT
        coalesce(cast(epk_id AS bigint), -1) AS epk_id,
        month_part,
        min(fst_exec_dt) AS fst_exec_dt,
        max(lst_exec_dt) AS lst_exec_dt,
        cast(sum(exec_rub_total) AS decimal(38, 15)) AS exec_rub_total,
        sum(exec_qty) AS exec_qty,
        cast(sum(exec_rub_atm) AS decimal(38, 15)) AS exec_rub_atm,
        sum(exec_atm_qty) AS exec_atm_qty,
        cast(sum(exec_rub_mobil) AS decimal(38, 15)) AS exec_rub_mobil,
        sum(exec_mobil_qty) AS exec_mobil_qty,
        cast(sum(exec_rub_web) AS decimal(38, 15)) AS exec_rub_web,
        sum(exec_web_qty) AS exec_web_qty,
        cast(sum(exec_rub_atm + exec_rub_mobil + exec_rub_web) AS decimal(38, 15)) AS exec_rub_main,
        sum(exec_atm_qty + exec_mobil_qty + exec_web_qty) AS exec_main_qty,
        cast(sum(exec_rub_mb) AS decimal(38, 15)) AS exec_rub_mb,
        sum(exec_mb_qty) AS exec_mb_qty,
        cast(sum(exec_rub_other) AS decimal(38, 15)) AS exec_rub_other,
        sum(exec_other_qty) AS exec_other_qty
    FROM custom_rb_sbol.sbol_oper_aggr
    WHERE month_part < ${current_month}
    GROUP BY coalesce(cast(epk_id AS bigint), -1), month_part
)
SELECT
    epk_id,
    month_part,
    fst_exec_dt AS sbol_fst_txn_dt,
    lst_exec_dt AS sbol_lst_txn_dt,
    cast(min(fst_exec_dt) OVER (PARTITION BY epk_id ORDER BY month_part ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS string) AS sbol_fst_txn_ever_dt,
    cast(max(lst_exec_dt) OVER (PARTITION BY epk_id ORDER BY month_part ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS string) AS sbol_lst_txn_ever_dt,
    exec_rub_total AS sbol_txn_1m_amt,
    exec_qty AS sbol_txn_1m_qty,
    cast(sum(exec_rub_total) OVER (PARTITION BY epk_id ORDER BY month_part ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS decimal(38, 15)) AS sbol_txn_3m_amt,
    sum(exec_qty) OVER (PARTITION BY epk_id ORDER BY month_part ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS sbol_txn_3m_qty,
    exec_rub_atm AS sbol_txn_atm_1m_amt,
    exec_atm_qty AS sbol_txn_atm_1m_qty,
    cast(sum(exec_rub_atm) OVER (PARTITION BY epk_id ORDER BY month_part ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS decimal(38, 15)) AS sbol_txn_atm_3m_amt,
    sum(exec_atm_qty) OVER (PARTITION BY epk_id ORDER BY month_part ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS sbol_txn_atm_3m_qty,
    exec_rub_mobil AS sbol_txn_mob_1m_amt,
    exec_mobil_qty AS sbol_txn_mob_1m_qty,
    cast(sum(exec_rub_mobil) OVER (PARTITION BY epk_id ORDER BY month_part ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS decimal(38, 15)) AS sbol_txn_mob_3m_amt,
    sum(exec_mobil_qty) OVER (PARTITION BY epk_id ORDER BY month_part ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS sbol_txn_mob_3m_qty,
    exec_rub_web AS sbol_txn_web_1m_amt,
    exec_web_qty AS sbol_txn_web_1m_qty,
    cast(sum(exec_rub_web) OVER (PARTITION BY epk_id ORDER BY month_part ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS decimal(38, 15)) AS sbol_txn_web_3m_amt,
    sum(exec_web_qty) OVER (PARTITION BY epk_id ORDER BY month_part ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS sbol_txn_web_3m_qty,
    exec_rub_main AS sbol_txn_main_1m_amt,
    exec_main_qty AS sbol_txn_main_1m_qty,
    cast(sum(exec_rub_main) OVER (PARTITION BY epk_id ORDER BY month_part ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS decimal(38, 15)) AS sbol_txn_main_3m_amt,
    sum(exec_main_qty) OVER (PARTITION BY epk_id ORDER BY month_part ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS sbol_txn_main_3m_qty,
    exec_rub_mb AS sbol_txn_mb_1m_amt,
    exec_mb_qty AS sbol_txn_mb_1m_qty,
    cast(sum(exec_rub_mb) OVER (PARTITION BY epk_id ORDER BY month_part ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS decimal(38, 15)) AS sbol_txn_mb_3m_amt,
    sum(exec_mb_qty) OVER (PARTITION BY epk_id ORDER BY month_part ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS sbol_txn_mb_3m_qty,
    exec_rub_other AS sbol_txn_other_1m_amt,
    exec_other_qty AS sbol_txn_other_1m_qty,
    cast(sum(exec_rub_other) OVER (PARTITION BY epk_id ORDER BY month_part ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS decimal(38, 15)) AS sbol_txn_other_3m_amt,
    sum(exec_other_qty) OVER (PARTITION BY epk_id ORDER BY month_part ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS sbol_txn_other_3m_qty,
    months_between(date_add(add_months(concat(month_part, '-01'), 1), -1), cast(min(fst_exec_dt) OVER (PARTITION BY epk_id ORDER BY month_part ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS timestamp)) AS sbol_mnth_fst_dt_qty,
    months_between(date_add(add_months(concat(month_part, '-01'), 1), -1), cast(max(lst_exec_dt) OVER (PARTITION BY epk_id ORDER BY month_part ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS timestamp)) AS sbol_mnth_lst_dt_qty
FROM monthly;
