{
 "title": "Masspers Internal Datamarts",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "schema", "query": "dc.custom.rozn.masspers.*" },
   {
    "name": "datamart",
    "query": "dc.custom.rozn.masspers.$schema.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Datamart build time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(dc.custom.rozn.masspers.$schema.$datamart.elapsed_time, 4, 5, 6)"
    }
   ]
  },
  {
   "title": "Datamart metrics",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 7 },
   "targets": [
    {
     "target": "alias(dc.custom.rozn.masspers.$schema.$datamart.elapsed_time, 'elapsed')"
    },
    {
     "target": "alias(dc.custom.rozn.masspers.$schema.$datamart.executor_run_time, 'executor_run_time')"
    },
    {
     "target": "alias(dc.custom.rozn.masspers.$schema.$datamart.executor_memory, 'executor_memory')"
    },
    {
     "target": "alias(dc.custom.rozn.masspers.$schema.$datamart.executors_amount, 'executors')"
    },
    {
     "target": "alias(dc.custom.rozn.masspers.$schema.$datamart.rows_count, 'rows')"
    },
    {
     "target": "alias(dc.custom.rozn.masspers.$schema.$datamart, 'as')"
    },
    {
     "target": "alias(dc.custom.rozn.masspers.$schema.$datamart.dir_size_bytes, 'size')"
    },
    {
     "target": "alias(dc.custom.rozn.masspers.$schema.$datamart.is_first_loading, 'first_loading')"
    },
    {}
   ]
  },
  {
   "title": "Last Metric For Datamarts",
   "type": "table",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 7 },
   "targets": [
    {
     "target": "aliasSub(aliasByNode(scale(dc.custom.rozn.masspers.$schema.$datamart.elapsed_time, 0.0000166666), 4, 5, 6), '(.*).elapsed_time', '\\1: elapsed (min)')"
    },
    {
     "target": "aliasSub(aliasByNode(scale(dc.custom.rozn.masspers.$schema.$datamart.executor_run_time, 0.000000277777), 4, 5, 6), '(.*).executor_run_time', '\\1: executor_run_time (hours)')"
    },
    {
     "target": "aliasByNode(dc.custom.rozn.masspers.$schema.$datamart.executor_memory, 4, 5, 6)"
    },
    {
     "target": "aliasByNode(dc.custom.rozn.masspers.$schema.$datamart.executors_amount, 4, 5, 6)"
    },
    {
     "target": "aliasByNode(dc.custom.rozn.masspers.$schema.$datamart.rows_count, 4, 5, 6)"
    },
    {
     "target": "aliasSub(aliasByNode(scale(dc.custom.rozn.masspers.$schema.$datamart.dir_size_bytes, 0.00000000093132), 4, 5, 6), '(.*).dir_size_bytes', '\\1: size (GB)')"
    },
    {
     "target": "aliasByNode(dc.custom.rozn.masspers.$schema.$datamart.is_first_loading, 4, 5, 6)"
    }
   ]
  },
  {
   "title": "Allocated executors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(dc.custom.rozn.masspers.$schema.$datamart.allocated_executors, 4, 5)"
    }
   ]
  }
 ]
}